freebsd_instance:
  image_family: freebsd-12-2-snap

iocage_tests_task:
  create_pool_script:
    - truncate -s 20G /root/poolfile
    - zpool create pool /root/poolfile
  install_pkgs_script:
    - sed -i '' 's/quarterly/latest/g' /etc/pkg/FreeBSD.conf
    - pkg install -y git python3 py37-sqlite3
  configure_python_script:
    - python3 -m ensurepip
  pip_cache:
    folder: ~/.cache/pip
    populate_script:
      - python3 install -r requirements-test.txt
      - python3 -m pip install -U cython
  env_setup_script:
    - python3 -m pip install -U -r requirements-test.txt
    - mount -t fdescfs null /dev/fd
    - pkg install -y devel/py-libzfs
  install_iocage_script:
    - python3 setup.py install
  test_script: pytest --zpool=pool tests/functional_tests
